---
title: "Client Report - Flights: Creating New Columns"
subtitle: "Unit 2 Task 1"
author: "John Wendt"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import polars.selectors as cs
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```



```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```

## Defining Season

1. __Create a new 'season' column.__ Define 'season' as:
    1. Winter for January, Febuary (note the mispelling), March
    1. Spring for April, May, June
    1. Summer for  July, August, September
    1. Fall for October, November, December
    1. All other rows can be assigned a value of 'Unknown' 

```{python}
df = (
  df.with_columns((
    pl.when((pl.col("month")=="January")|(pl.col("month")=="Febuary")|(pl.col("month")=="March")).then(pl.lit("Winter"))
    .when((pl.col("month")=="April")|(pl.col("month")=="May")|(pl.col("month")=="June")).then(pl.lit("Spring"))
    .when((pl.col("month")=="July")|(pl.col("month")=="August")|(pl.col("month")=="September")).then(pl.lit("Summer"))
    .when((pl.col("month")=="October")|(pl.col("month")=="November")|(pl.col("month")=="December")).then(pl.lit("Fall"))
    .otherwise(pl.lit("Unknown"))
  ).alias("Season"))
)
```

## Filtration and division

1. __Divide all the columns by 1000 whose name starts with num_of.__ Be sure to first filter out rows that contain problematic values for the columns like -999 or 1500+.

```{python}
df = (
  df.filter(~(pl.col("num_of_delays_carrier").is_in(["1500+","-999"])))
  .filter(~(pl.col("num_of_flights_total").is_in([-999])))
  .filter(~(pl.col("num_of_delays_late_aircraft").is_in([-999])))
  .filter(~(pl.col("num_of_delays_nas").is_in([-999])))
  .filter(~(pl.col("num_of_delays_security").is_in([-999])))
  .filter(~(pl.col("num_of_delays_weather").is_in([-999])))
  .filter(~(pl.col("num_of_delays_total").is_in([-999])))
  .filter(~(pl.all_horizontal(pl.col("*").is_null()))) #all horizontal is not in reading but errors kept suggesting i try it so we learned. col"*" selects all
  .with_columns(pl.col("num_of_delays_carrier").cast(pl.Int64))
  .with_columns(cs.starts_with("num_of")/1000)
)
```

## Correcting data

1. According to the BTS website, the “Weather” category only accounts for severe weather delays. Mild weather delays are not counted in the “Weather” category, but are actually included in both the “nas” and “late_aircraft” categories. __Using the columns you modified in the bullet above, your job is to create a new column that calculates the total number of flights (in 1,000's) delayed by weather (both severe and mild).__ Show your work by printing the first 5 rows of the dataset. Use these three rules for your calculations:  

    a. 100% of delayed flights in the Weather category are due to weather  
    a. 30% of all delayed flights in the "late_aircraft" category are due to weather  
    a. From April through August, 40% of delayed flights in the NAS category are due to weather. The rest of the months, the proportion rises to 65%  

```{python}
df = (
  df.with_columns((
    pl.col("minutes_delayed_weather")+
    pl.col("minutes_delayed_late_aircraft")*0.3+
    pl.when((pl.col("Season") == "Spring")|(pl.col("Season") == "Summer")&~(pl.col("month") == "September"))
    .then(pl.col("minutes_delayed_nas")*0.4)
    .otherwise(pl.col("minutes_delayed_nas")*0.65)
  )
  .alias("minutes_delayed_weather_all"))
)
df.head()
```

## Visualizing

1. __Using the new weather variable calculated above, create a boxplot showing the distribution of flights delayed by weather for each season. Describe what you learn from this graph.__    

_As described in the prompts above, a dataset on airports has been wrangled to condense months into specific seasons, and correct discrepancies. As seen in prompt 3, delay due to weather is noticeably higher in the darker months (fall and winter) than the others. Spring can be seen to have the lowest average delay and the lowest extreme delay. This can indicate that the most reliable time to fly may be in the Spring months (April-June)._

_It may be noticed that some of these numbers are in the hundreds of thousands, and it must be addressed that these delays are aggregated among sometimes a hundred plane gates at a time, and aggregated among an entire month. Because of this, it can be calculated that a statistic of 450,000 minutes delay averages out to an 18 minute delay in an average airport and a 9 minute delay in larger airports such as LAX; per plane._

_Observing numerically, most of the averages are similar, all plus or minus 3,000 minutes of the other. This could indicate that weather may only affect delay in extreme cases. This could further be proven by noting that the original data file only tracked delay in extreme weather._

```{python}
aplot = (
  ggplot(df,aes(x="Season",y="minutes_delayed_weather_all"))
  +geom_boxplot()
  +labs(
    title="How often is a plane delayed?",
    y="Weather Delay (minutes)"
  )
)
aplot
```