---
title: "Client Report - Exploring Names"
subtitle: "Unit 1 Task 1"
author: "John Wendt"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```

## What was the earliest year that the name ‘Felisha’ was used?

The name Felisha, though a variant of the name Felicia, is not as uncommon as one would think. The first recording of this exact spelling was **1964**, and last recorded in 2007.

```{python}
adf = (
  df.select("name","year")
  .filter(pl.col("name")=="Felisha")
  .sort(by=["year"])
)
#adf
```


## What year had the most babies named ‘David’? How many babies were named ‘David’ that year?

The name David is quite a popular name. It was most popular in the late 50s and early 60s. The most popular year was **1955**, where 86,389 children were named David.

_AI use reflection_
**Link** to the original chat: https://share.gemini.google/EfMs1Cx5y6WU
**The Process** I wanted help in trying to count how many times a specific name showed up in a year. However, I had misunderstood how to do this problem.
**The Impact**  Since I misunderstood the problem, the AI Chatbot was not able to help me resolve my issue. I had to further ponder and eventually realised the data set had a "totals section". I could use that to organize. The AI did not help me learn, however since I used it in the process I must note that I have.

```{python}
bdf = (
  df.select("name","year","Total")
  .filter(pl.col("name")=="David")
  .sort(by=["Total"], descending=True)
)
#bdf
```


## What year did the author's name hit its peak? How many babies were named the same name in that year?

The author's name is John. This is quite a popular name, being one of the main Biblical names. The most popular year for the name John is **1947**, where **88,474** babies were named the same. However, it has been on a general decline since the least popular years for this name are all within the past 7 years.

```{python}
cdf = (
  df.select("name","year","Total")
  .filter(pl.col("name")=="John")
  .sort(by=["Total"],descending=True)
)
#cdf
```


## In the most recent year, what was the most common female name in Utah?

The most recent year, 2025, is not listed among the data. However, 2024 is recorded. The most common name was Oliver. However, again, this question is asking for the most common female name. The 6th most common name overall, 1st most common female name is **Olivia**. In the most recent recorded year, 2024, Olivia was most common with 215 children being named that.

```{python}
ddf = (
  df.select("name","year","UT")
  .filter(pl.col("year")==2024)
  .sort("UT",descending=True)
)
#ddf.head(10)
```


---
