---
title: "Client Report - What's in a Name?"
subtitle: "Unit 1 Task 2"
author: "John Wendt"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)

df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```

## The name John

__How does the author's name at their birth year compare to its use historically?__ 

The author's name is John. The name John was most popular in the mid-early 20th century, well before the author's birth date of 2004 indicated by the red line. Although the name is on a heavy downtrend since its popularity, it is still quite popular with around 8,000 people being born with this name yearly

```{python}
adf = (
  df.select("name","year","Total")
  .filter(pl.col("name")=="John")
)
aplot = (
  ggplot(adf,aes(x="year",y="Total"))
  +geom_point(color="black",size=2)
  +geom_smooth(method="loess",color="blue")
  +scale_x_continuous(format="d") #this was difficult, would have been nice to know it was later in the reading
  +geom_vline(xintercept=2003.5,color="red",size="0.5")
  +labs(
    title="The name John throughout the years",
    x="Year",
    y="Babies with this name"
  )
)
aplot
```


## Forrest Gump

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

Forrest Gump is the main character of the wildly popular movie named the same. This movie came out in 1994, indicated by the red line on the chart, but still affects pop culture to this day. Due to its mass popularity, children born both before and after this time were increasingly named Forrest. Notably in the year this movie was published the name nearly quintupled in popularity.

```{python}
bdf = (
  df.select("name","year","Total")
  .filter(pl.col("name")=="Forrest")
)
bplot = (
  ggplot(bdf,aes(x="year",y="Total"))
  +geom_point(color="black",size=2)
  +geom_smooth(method="loess",color="blue")
  +scale_x_continuous(format="d")
  +geom_vline(xintercept=1993.5,color="red",size="0.5")
  +labs(
    title="The name Forrest throughout the years",
    subtitle="The movie Forrest Gump came out in 1994, heavily popularizing\nthe name Forrest",
    x="Year",
    y="Babies with this name"
  )
)
bplot
```

## Biblical names

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__  

These Christian names, like all Christian names, were and are wildly popular. Even today thousands of children each year are born with any given Christian name. Two of these names show to be more popular than the others; Paul, and mainly Mary. These could be due to the popularity of these individual people or due to pop idols named similarly.

```{python}
cdf = (
  df.select("name","year","Total")
  .filter((pl.col("name")=="Mary")|(pl.col("name")=="Martha")|(pl.col("name")=="Peter")|(pl.col("name")=="Paul"))
  .filter((pl.col("year")>=1920)&(pl.col("year")<=2000))
)
cplot = (
  ggplot(cdf,aes(x="year",y="Total",color="name"))
  +geom_point(size=2)
  +geom_smooth(method="loess",se=False)
  +scale_x_continuous(format="d")
  +labs(
    title="Mary, Martha, Peter, and Paul",
    x="Year",
    y="Babies with these name"
  )
)
cplot
```