---
title: "Client Report - Project 0: Introduction"
subtitle: "Course DS 250"
author: "John Wendt"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn more about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
from palmerpenguins import load_penguins
penguins = load_penguins()
```

## QUESTION|TASK 1

Below is listed metrics such as species, island, length, mass, sex, and year. These metrics are of penguins researched at Palmer Archipelago in Antarctica between the years 2007 and 2009. The study was originally to track foraging and sexual behaviors as well as adaptability. However, this dataset became widely used among the programming and data science community in late 2020. This table includes the first and last five of the total and unorganized dataset. This dataset is sorted by species, starting with the Adelie species, next the Gentoo species, and finishing with the Chinstrap species.
```{python}
# To recreate the table, all you should need to do is run this code, no editing required
penguins

```


## QUESTION|TASK 2

Below is an interactive graph of penguin flipper length vs body mass. The trend is generally proportional, meaning that as the flipper length increases the body mass also increses, as shown by the pink line. Each different species is indicated by different shape and color to easily differentiate between. All data between the same species is roughly similar and within a range; the Chinstrap being slightly larger than the Adelie and the Gentoo being significantly larger than the other two species.
```{python}
# Include and execute your code here
(
    ggplot(penguins, aes(x="flipper_length_mm", y="body_mass_g"))
    + geom_point(aes(color="species", shape="species"))
    + geom_smooth(method="lm")
    + labs(
        title="Body mass and flipper length",
        subtitle="Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x="Flipper length (mm)",
        y="Body mass (g)",
        color="Species",
        shape="Species",
    )
)

```
